import React,{useMemo,useState}from'react';import'./styles.css';
const brl=v=>v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const produtos=[['Arroz Branco 5kg','Tio João','Grãos',120,18.9,26.9,'Em Estoque','🍚'],['Óleo de Soja 900ml','Liza','Óleos',88,6.2,8.49,'Em Estoque','🛢️'],['Leite Integral 1L','Piracanjuba','Laticínios',0,4.1,5.79,'Fora de Estoque','🥛'],['Feijão Preto 1kg','Camil','Grãos',18,7.5,9.99,'Estoque Baixo','🫘'],['Açúcar Cristal 1kg','União','Mercearia',14,4.3,6.29,'Estoque Baixo','🍬'],['Café Torrado 500g','Pilão','Bebidas',56,12.6,17.99,'Em Estoque','☕'],['Macarrão 500g','Adria','Massas',32,2.4,3.49,'Em Estoque','🍝'],['Detergente 500ml','Ypê','Limpeza',6,1.95,2.79,'Estoque Baixo','🧴'],['Sabão em Pó 1kg','Omo','Limpeza',0,10.9,14.9,'Fora de Estoque','🧼'],['Papel Higiênico 12x30m','Neve','Higiene',21,14.5,19.9,'Em Estoque','🧻']].map((p,i)=>({id:i+1,nome:p[0],marca:p[1],cat:p[2],qtd:p[3],custo:p[4],preco:p[5],status:p[6],ico:p[7]}));
function App(){const[p,setP]=useState('Dashboard'),[dark,setDark]=useState(false),[cat,setCat]=useState('Todos'),[cart,setCart]=useState([{...produtos[0],n:1},{...produtos[1],n:1},{...produtos[5],n:1}]);const cats=['Todos',...new Set(produtos.map(x=>x.cat))],vis=cat==='Todos'?produtos:produtos.filter(x=>x.cat===cat);const sub=useMemo(()=>cart.reduce((s,x)=>s+x.preco*x.n,0),[cart]),imp=sub*.1,desc=sub>50?5:0,total=sub+imp-desc;function add(x){if(!x.qtd)return;setCart(c=>c.find(i=>i.id===x.id)?c.map(i=>i.id===x.id?{...i,n:i.n+1}:i):[...c,{...x,n:1}])}function qtd(id,v){setCart(c=>c.map(i=>i.id===id?{...i,n:Math.max(1,i.n+v)}:i))}return <main className={dark?'app dark':'app'}><aside><b className='logo'>LOGO</b>{['Dashboard','Itens','PDV','Relatório de Vendas','Fornecedores','Configurações'].map(x=><button className={p===x?'on':''} onClick={()=>setP(x)}>{x}</button>)}<small>Sistema de PDV e Gestão</small></aside><section className='content'><header><div><span>POS</span><h1>{p}</h1></div><input placeholder='Pesquisar...'/><button onClick={()=>setDark(!dark)}>{dark?'☀️':'🌙'}</button></header>{p==='Dashboard'&&<Dashboard/>}{p==='Itens'&&<Itens/>}{p==='PDV'&&<PDV vis={vis} cats={cats} cat={cat} setCat={setCat} cart={cart} add={add} qtd={qtd} rm={id=>setCart(cart.filter(i=>i.id!==id))} sub={sub} imp={imp} desc={desc} total={total}/>} {p==='Relatório de Vendas'&&<Simple title='Relatório de Vendas' text='Área preparada para gráficos, exportação e filtros por período.'/ >}{p==='Fornecedores'&&<Simple title='Fornecedores' text='Cadastre fornecedores, contatos, CNPJ e histórico de compras.'/ >}{p==='Configurações'&&<Simple title='Configurações' text='Configure usuários, permissões, pagamentos, impostos e impressão.'/ >}</section></main>}
function Card({t,v,s}){return <div className='card'><p>{t}</p><h2>{v}</h2><small>{s}</small></div>}
function Dashboard(){return <div className='page'><div className='cards'><Card t='Vendas Totais' v='R$ 30.450,00' s='+12,5% vs semana anterior'/><Card t='Receita Total' v='R$ 52.890,00' s='+15,3% vs semana anterior'/><Card t='Itens com Estoque Baixo' v='13' s='Verifique os itens'/><Card t='Itens em Falta' v='09' s='Verifique os itens'/></div><div className='two'><section className='panel'><h3>Vendas da Semana</h3><div className='bars'>{[35,70,48,88,62,76,44].map((h,i)=><i style={{height:h+'%'}} key={i}/>)}</div><div className='days'><span>Dom</span><span>Seg</span><span>Ter</span><span>Qua</span><span>Qui</span><span>Sex</span><span>Sáb</span></div></section><section className='panel'><h3>Resumo de Estoque</h3><div className='donut'><b>824</b><span>Itens</span></div><p>🟢 Em Estoque 642</p><p>🟡 Estoque Baixo 112</p><p>🔴 Fora de Estoque 70</p></section></div><Tabela titulo='Itens com Estoque Baixo' lista={produtos.filter(x=>x.status!=='Em Estoque')}/></div>}
function Itens(){return <div className='page'><div className='actions'><button>Filtrar por Categoria</button><button>Filtrar por Status</button><button className='primary'>Adicionar Item</button></div><Tabela titulo='Itens' lista={produtos}/></div>}
function Tag({s}){return <span className={'tag '+s.toLowerCase().replaceAll(' ','-')}>{s}</span>}
function Tabela({titulo,lista}){return <section className='panel'><h3>{titulo}</h3><div className='table'><div className='thead'><b>Nome do Item</b><b>Marca</b><b>Categoria</b><b>Qtd.</b><b>Compra</b><b>Venda</b><b>Status</b></div>{lista.map(p=><div className='tr'><span>{p.ico} {p.nome}</span><span>{p.marca}</span><span>{p.cat}</span><span>{p.qtd} un.</span><span>{brl(p.custo)}</span><span>{brl(p.preco)}</span><span><Tag s={p.status}/></span></div>)}</div></section>}
function PDV({vis,cats,cat,setCat,cart,add,qtd,rm,sub,imp,desc,total}){return <div className='page pdv'><section><div className='actions'><input placeholder='Pesquisar produtos...'/><button className='primary'>Ler Código de Barras</button></div><div className='tabs'>{cats.map(c=><button className={cat===c?'on':''} onClick={()=>setCat(c)}>{c}</button>)}</div><div className='products'>{vis.map(p=><article><div>{p.ico}</div><h3>{p.nome}</h3><p>{p.qtd} un. em estoque</p><strong>{brl(p.preco)}</strong><button disabled={!p.qtd} onClick={()=>add(p)}>Adicionar</button></article>)}</div></section><aside className='cart'><h2>Detalhes do Carrinho</h2><small>#PDV-000125</small>{cart.map(p=><div className='cartitem'><span>{p.ico}</span><b>{p.nome}</b><button onClick={()=>qtd(p.id,-1)}>-</button><em>{p.n}</em><button onClick={()=>qtd(p.id,1)}>+</button><button onClick={()=>rm(p.id)}>×</button></div>)}<div className='totais'><p><span>Subtotal</span><b>{brl(sub)}</b></p><p><span>Imposto (10%)</span><b>{brl(imp)}</b></p><p><span>Desconto</span><b>- {brl(desc)}</b></p><h3><span>Total a Pagar</span><b>{brl(total)}</b></h3></div><div className='pay'><button>Dinheiro</button><button>Cartão</button><button>Pix</button></div><button className='continuar'>Continuar</button></aside></div>}
function Simple({title,text}){return <div className='page'><div className='cards'><Card t='Ticket Médio' v='R$ 47,80' s='Hoje'/><Card t='Lucro Estimado' v='R$ 8.240,00' s='Este mês'/><Card t='Clientes Atendidos' v='1.248' s='Este mês'/></div><section className='panel'><h3>{title}</h3><p>{text}</p></section></div>}
export default App;
